#:kivy 2.1.0

WindowManager:
    MainScreen:

<MainScreen>
    name: 'main'
    FloatLayout:
        #Image:
            #id: bg
            #source: 'datafiles/images/titlebck.png'
            #pos:(0,0)
        Label:
            text: 'SETUP'
            pos:(-350, 320)
            font_name: "datafiles/fonts/Ubuntu-M.ttf"
            outline_color: (0.78, 0.22, 0.22, 1)
            outline_width: 3
            font_size: 50
        RelativeLayout:
            pos: (0, 0)
            Label:
                text: 'OPPONENT FIELD TYPE'
                pos:(-490, 270)
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                outline_color: (0.78, 0.22, 0.22, 1)
                outline_width: 2
                font_size: 24
            CheckBox:
                pos: (-605, 230)
                background_checkbox_normal: "datafiles/images/check_empty.png"
        RelativeLayout:
            pos: (70, 0)
            Button:
                text: 'DLC\nCHECK'
                size_hint: (.07, .09)
                halign: 'center'
                pos:(0, 28)
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 22
                background_normal: ''
                background_color: '#c83737ff'
                on_release: print('DLC CHECK')
            Button:
                text: 'GENERATE'
                size_hint: (.15, .13)
                pos:(120, 16)
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 32
                background_normal: ''
                background_color: '#c83737ff'
                on_release: print('GENERATE')
            Button:
                text: 'ABOUT'
                size_hint: (.07, .09)
                halign: 'center'
                pos:(340, 28)
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 22
                background_normal: ''
                background_color: '#c83737ff'
                on_release: print('ABOUT')
        RelativeLayout:
            size_hint: (.005, .95)
            pos: (0, 0)
            canvas.before:
                Color:
                    rgba: 1, 1, 1, 1
                Rectangle:
                    pos: (574,16)
                    size: self.size
        