#:kivy 2.1.0

WindowManager:
    MainScreen:

<MainScreen>
    name: 'main'
    singleclass: singleclass
    multiclass: multiclass
    shortlength: shortlength
    mediumlength: mediumlength
    longlength: longlength
    endurancelength: endurancelength
    raining: raining
    norain: norain
    class1: class1
    class2: class2
    class3: class3
    class4: class4
    class5: class5
    trackname: trackname
    duration: duration
    starttime: starttime
    weather1: weather1
    weather2: weather2
    weather3: weather3
    weather4: weather4
    starttype: starttype
    pitstop: pitstop
    sfcy: sfcy
    fcy: fcy

    FloatLayout:
        #Image:
            #id: bg
            #source: 'datafiles/images/titlebck.png'
            #pos:(0,0)
        Label:
            text: 'SETUP'
            pos:(-350, 320)
            font_name: "datafiles/fonts/Ubuntu-M.ttf"
            outline_color: (0.78, 0.22, 0.22, 1)
            outline_width: 3
            font_size: 50
        RelativeLayout:
            pos: (0, 0)
            Label:
                text: 'OPPONENT FIELD TYPE'
                pos:(-490, 270)
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                outline_color: (0.78, 0.22, 0.22, 1)
                outline_width: 2
                font_size: 24
            Label:
                text: 'Single Class'
                pos:(-515, 235)
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 24
            CheckBox:
                id: singleclass
                group: "opponent field"
                pos: (20, 571)
                size_hint: (None, None)
                size: (30, 25)
                active: True
                background_radio_normal: "datafiles/images/check_empty.png"
                background_radio_down: "datafiles/images/check_marked.png"
            Label:
                text: 'Multi-class'
                pos:(-315, 235)
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 24
            CheckBox:
                id: multiclass
                group: "opponent field"
                pos: (220, 571)
                size_hint: (None, None)
                size: (30, 25)
                background_radio_normal: "datafiles/images/check_empty.png"
                background_radio_down: "datafiles/images/check_marked.png"
        RelativeLayout:
            pos: (0, 0)
            Label:
                text: 'RACE LENGTH'
                pos:(-542, 170)
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                outline_color: (0.78, 0.22, 0.22, 1)
                outline_width: 2
                font_size: 24
            Label:
                text: 'Short'
                pos:(-550, 135)
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 24
            CheckBox:
                id: shortlength
                group: "race length"
                pos: (20, 471)
                size_hint: (None, None)
                size: (30, 25)
                active: True
                background_radio_normal: "datafiles/images/check_empty.png"
                background_radio_down: "datafiles/images/check_marked.png"
            Label:
                text: 'Medium'
                pos:(-400, 135)
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 24
            CheckBox:
                id: mediumlength
                group: "race length"
                pos: (155, 471)
                size_hint: (None, None)
                size: (30, 25)
                background_radio_normal: "datafiles/images/check_empty.png"
                background_radio_down: "datafiles/images/check_marked.png"
            Label:
                text: 'Long'
                pos:(-555, 95)
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 24
            CheckBox:
                id: longlength
                group: "race length"
                pos: (20, 431)
                size_hint: (None, None)
                size: (30, 25)
                active: True
                background_radio_normal: "datafiles/images/check_empty.png"
                background_radio_down: "datafiles/images/check_marked.png"
            Label:
                text: 'Endurance'
                pos:(-386, 95)
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 24
            CheckBox:
                id: endurancelength
                group: "race length"
                pos: (155, 431)
                size_hint: (None, None)
                size: (30, 25)
                background_radio_normal: "datafiles/images/check_empty.png"
                background_radio_down: "datafiles/images/check_marked.png"
        RelativeLayout:
            pos: (0, 0)
            Label:
                text: 'RAINING CONDITIONS'
                pos:(-495, 30)
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                outline_color: (0.78, 0.22, 0.22, 1)
                outline_width: 2
                font_size: 24
            Label:
                text: 'Add rain weathers'
                pos:(-480, -5)
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 24
            CheckBox:
                id: raining
                group: "raining conditions"
                pos: (20, 331)
                size_hint: (None, None)
                size: (30, 25)
                active: True
                background_radio_normal: "datafiles/images/check_empty.png"
                background_radio_down: "datafiles/images/check_marked.png"
            Label:
                text: 'Remove rain weathers'
                pos:(-456, -45)
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 24
            CheckBox:
                id: norain
                group: "raining conditions"
                pos: (20, 291)
                size_hint: (None, None)
                size: (30, 25)
                active: True
                background_radio_normal: "datafiles/images/check_empty.png"
                background_radio_down: "datafiles/images/check_marked.png"
        RelativeLayout:
            pos: (0, 0)
            Label:
                text: 'CLASSES:'
                valign: 'bottom'
                halign: 'left'
                pos: (600, 645)
                size_hint: (1, 1)
                text_size: self.size
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                outline_color: (0.78, 0.22, 0.22, 1)
                outline_width: 2
                font_size: 28
            Image:
                id: class1
                source: 'datafiles/images/class_null.png'
                pos:(130, 310)
            Image:
                id: class2
                source: 'datafiles/images/class_null.png'
                pos:(210, 310)
            Image:
                id: class3
                source: 'datafiles/images/class_null.png'
                pos:(290, 310)
            Image:
                id: class4
                source: 'datafiles/images/class_null.png'
                pos:(370, 310)
            Image:
                id: class5
                source: 'datafiles/images/class_null.png'
                pos:(450, 310)
            Label:
                text: 'TRACK:'
                valign: 'bottom'
                halign: 'left'
                pos: (600, 585)
                size_hint: (1, 1)
                text_size: self.size
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                outline_color: (0.78, 0.22, 0.22, 1)
                outline_width: 2
                font_size: 28
            Label:
                id: trackname
                text: 'Spa-Franchorchamps 2022'
                valign: 'bottom'
                halign: 'left'
                pos: (715, 587)
                size_hint: (1, 1)
                text_size: self.size
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 26
            Label:
                text: 'DURATION:'
                valign: 'bottom'
                halign: 'left'
                pos: (600, 525)
                size_hint: (1, 1)
                text_size: self.size
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                outline_color: (0.78, 0.22, 0.22, 1)
                outline_width: 2
                font_size: 28
            Label:
                id: duration
                text: '20 minutes +1 lap'
                valign: 'bottom'
                halign: 'left'
                pos: (770, 527)
                size_hint: (1, 1)
                text_size: self.size
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 26
            Label:
                text: 'START TIME:'
                valign: 'bottom'
                halign: 'left'
                pos: (600, 463)
                size_hint: (1, 1)
                text_size: self.size
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                outline_color: (0.78, 0.22, 0.22, 1)
                outline_width: 2
                font_size: 28
            Label:
                id: starttime
                text: '22h - 22x progression'
                valign: 'bottom'
                halign: 'left'
                pos: (780, 465)
                size_hint: (1, 1)
                text_size: self.size
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 26
            Label:
                text: 'WEATHER FORECAST (sync to race)'
                valign: 'bottom'
                halign: 'left'
                pos: (600, 401)
                size_hint: (1, 1)
                text_size: self.size
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                outline_color: (0.78, 0.22, 0.22, 1)
                outline_width: 2
                font_size: 28
            Image:
                id: weather1
                source: 'datafiles/images/weather_null.png'
                pos:(45, 10)
            Image:
                id: weather2
                source: 'datafiles/images/weather_null.png'
                pos:(145, 10)
            Image:
                id: weather3
                source: 'datafiles/images/weather_null.png'
                pos:(245, 10)
            Image:
                id: weather4
                source: 'datafiles/images/weather_null.png'
                pos:(345, 10)
            Label:
                text: 'START TYPE:'
                valign: 'bottom'
                halign: 'left'
                pos: (600, 265)
                size_hint: (1, 1)
                text_size: self.size
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                outline_color: (0.78, 0.22, 0.22, 1)
                outline_width: 2
                font_size: 28
            Label:
                id: starttype
                text: 'Standing'
                valign: 'bottom'
                halign: 'left'
                pos: (780, 267)
                size_hint: (1, 1)
                text_size: self.size
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 26
            Label:
                text: 'MANDATORY PIT STOP:'
                valign: 'bottom'
                halign: 'left'
                pos: (600, 203)
                size_hint: (1, 1)
                text_size: self.size
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                outline_color: (0.78, 0.22, 0.22, 1)
                outline_width: 2
                font_size: 28
            Label:
                id: pitstop
                text: '4x Tires'
                valign: 'bottom'
                halign: 'left'
                pos: (925, 205)
                size_hint: (1, 1)
                text_size: self.size
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 26
            Label:
                text: 'TRACK LIMIT WARNINGS:'
                valign: 'bottom'
                halign: 'left'
                pos: (600, 141)
                size_hint: (1, 1)
                text_size: self.size
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                outline_color: (0.78, 0.22, 0.22, 1)
                outline_width: 2
                font_size: 28
            Label:
                id: tracklimits
                text: '5'
                valign: 'bottom'
                halign: 'left'
                pos: (945, 143)
                size_hint: (1, 1)
                text_size: self.size
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 26
            Label:
                text: 'SCHEDULED FULL COURSE YELLOW:'
                valign: 'bottom'
                halign: 'left'
                pos: (600, 79)
                size_hint: (1, 1)
                text_size: self.size
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                outline_color: (0.78, 0.22, 0.22, 1)
                outline_width: 2
                font_size: 28
            Label:
                id: sfcy
                text: 'Random'
                valign: 'bottom'
                halign: 'left'
                pos: (1090, 81)
                size_hint: (1, 1)
                text_size: self.size
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 26
            Label:
                text: 'FULL COURSE YELLOWS:'
                valign: 'bottom'
                halign: 'left'
                pos: (600, 17)
                size_hint: (1, 1)
                text_size: self.size
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                outline_color: (0.78, 0.22, 0.22, 1)
                outline_width: 2
                font_size: 28
            Label:
                id: fcy
                text: 'Yes'
                valign: 'bottom'
                halign: 'left'
                pos: (935, 19)
                size_hint: (1, 1)
                text_size: self.size
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 26
        RelativeLayout:
            pos: (70, 0)
            Button:
                text: 'DLC\nCHECK'
                size_hint: (.07, .09)
                halign: 'center'
                pos:(0, 28)
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 22
                background_normal: ''
                background_color: '#c83737ff'
                on_release: print('DLC CHECK')
            Button:
                text: 'GENERATE'
                size_hint: (.15, .13)
                pos:(120, 16)
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 32
                background_normal: ''
                background_color: '#c83737ff'
                on_release: root.generate()
            Button:
                text: 'ABOUT'
                size_hint: (.07, .09)
                halign: 'center'
                pos:(340, 28)
                font_name: "datafiles/fonts/Ubuntu-M.ttf"
                font_size: 22
                background_normal: ''
                background_color: '#c83737ff'
                on_release: print('ABOUT')
        RelativeLayout:
            size_hint: (.005, .95)
            pos: (0, 0)
            canvas.before:
                Color:
                    rgba: 1, 1, 1, 1
                Rectangle:
                    pos: (574,16)
                    size: self.size
        