extends Node

@onready var sr_field_type_btn1 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label1/ftsettings1_radio1"
@onready var sr_field_type_btn2 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label1/ftsettings1_radio2"
@onready var sr_field_type_btn3 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label1/ftsettings1_radio3"
@onready var sr_field_type_btn4 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label1/ftsettings1_radio4"
@onready var sr_field_type_btn5 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label1/ftsettings1_radio5"
@onready var sr_field_type_btn6 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label1/ftsettings1_radio6"

@onready var sr_field_type_check1 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label2/ftsettings1_radio1"
@onready var sr_field_type_check2 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label2/ftsettings1_radio2"
@onready var sr_field_type_check3 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label2/ftsettings1_radio3"
@onready var sr_field_type_check4 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label2/ftsettings1_radio4"
@onready var sr_field_type_check5 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label2/ftsettings1_radio5"
@onready var sr_field_type_check6 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label2/ftsettings1_radio6"
@onready var sr_field_type_check7 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label2/ftsettings1_radio7"
@onready var sr_field_type_check8 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label2/ftsettings1_radio8"
@onready var sr_field_type_check9 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label2/ftsettings1_radio9"
@onready var sr_field_type_check10 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label2/ftsettings1_radio10"
@onready var sr_field_type_check11 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label2/ftsettings1_radio11"
@onready var sr_field_type_check12 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label2/ftsettings1_radio12"
@onready var sr_field_type_check13 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label2/ftsettings1_radio13"
@onready var sr_field_type_check14 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label2/ftsettings1_radio14"
@onready var sr_field_type_check15 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label2/ftsettings1_radio15"
@onready var sr_field_type_check16 = $"../single_race_screen/Control/singlerace_panel1/fieldtype_settings/ftsettings_label2/ftsettings1_radio16"

@onready var sr_race_length_btn1 = $"../single_race_screen/Control/singlerace_panel2/racelength_settings/rlsettings_label1/rlsettings1_radio1"
@onready var sr_race_length_btn2 = $"../single_race_screen/Control/singlerace_panel2/racelength_settings/rlsettings_label1/rlsettings1_radio2"
@onready var sr_race_length_btn3 = $"../single_race_screen/Control/singlerace_panel2/racelength_settings/rlsettings_label1/rlsettings1_radio3"
@onready var sr_race_length_btn4 = $"../single_race_screen/Control/singlerace_panel2/racelength_settings/rlsettings_label1/rlsettings1_radio4"
@onready var sr_race_length_btn5 = $"../single_race_screen/Control/singlerace_panel2/racelength_settings/rlsettings_label1/rlsettings1_radio5"
@onready var sr_race_length_btn6 = $"../single_race_screen/Control/singlerace_panel2/racelength_settings/rlsettings_label1/rlsettings1_radio6"
@onready var sr_race_length_btn7 = $"../single_race_screen/Control/singlerace_panel2/racelength_settings/rlsettings_label1/rlsettings1_radio7"
@onready var sr_race_length_btn8 = $"../single_race_screen/Control/singlerace_panel2/racelength_settings/rlsettings_label1/rlsettings1_radio8"
@onready var sr_race_length_btn9 = $"../single_race_screen/Control/singlerace_panel2/racelength_settings/rlsettings_label1/rlsettings1_radio9"
@onready var sr_race_length_btn10 = $"../single_race_screen/Control/singlerace_panel2/racelength_settings/rlsettings_label1/rlsettings1_radio10"

@onready var sr_time_period_btn1 = $"../single_race_screen/Control/singlerace_panel3/timeperiod_settings/tpsettings_label1/rlsettings1_radio1"
@onready var sr_time_period_btn2 = $"../single_race_screen/Control/singlerace_panel3/timeperiod_settings/tpsettings_label1/rlsettings1_radio2"
@onready var sr_time_period_btn3 = $"../single_race_screen/Control/singlerace_panel3/timeperiod_settings/tpsettings_label1/rlsettings1_radio3"

@onready var sr_time_progression_btn1 = $"../single_race_screen/Control/singlerace_panel3/timeperiod_settings/tpsettings_label2/tpsettings1_radio1"
@onready var sr_time_progression_btn2 = $"../single_race_screen/Control/singlerace_panel3/timeperiod_settings/tpsettings_label2/tpsettings1_radio2"
@onready var sr_time_progression_btn3 = $"../single_race_screen/Control/singlerace_panel3/timeperiod_settings/tpsettings_label2/tpsettings1_radio3"
@onready var sr_time_progression_btn4 = $"../single_race_screen/Control/singlerace_panel3/timeperiod_settings/tpsettings_label2/tpsettings1_radio4"
@onready var sr_time_progression_btn5 = $"../single_race_screen/Control/singlerace_panel3/timeperiod_settings/tpsettings_label2/tpsettings1_radio5"
@onready var sr_time_progression_btn6 = $"../single_race_screen/Control/singlerace_panel3/timeperiod_settings/tpsettings_label2/tpsettings1_radio6"
@onready var sr_time_progression_btn7 = $"../single_race_screen/Control/singlerace_panel3/timeperiod_settings/tpsettings_label2/tpsettings1_radio7"
@onready var sr_time_progression_btn8 = $"../single_race_screen/Control/singlerace_panel3/timeperiod_settings/tpsettings_label2/tpsettings1_radio8"
@onready var sr_time_progression_btn9 = $"../single_race_screen/Control/singlerace_panel3/timeperiod_settings/tpsettings_label2/tpsettings1_radio9"

@onready var sr_weather_btn1 = $"../single_race_screen/Control/singlerace_panel4/weather_settings/wsettings_label1/wsettings1_radio1"
@onready var sr_weather_btn2 = $"../single_race_screen/Control/singlerace_panel4/weather_settings/wsettings_label1/wsettings1_radio2"
@onready var sr_weather_btn3 = $"../single_race_screen/Control/singlerace_panel4/weather_settings/wsettings_label1/wsettings1_radio3"
@onready var sr_weather_btn4 = $"../single_race_screen/Control/singlerace_panel4/weather_settings/wsettings_label1/wsettings1_radio4"

@onready var sr_weather_slot_btn1 = $"../single_race_screen/Control/singlerace_panel4/weather_settings/wsettings_label2/wsettings1_radio1"
@onready var sr_weather_slot_btn2 = $"../single_race_screen/Control/singlerace_panel4/weather_settings/wsettings_label2/wsettings1_radio2"
@onready var sr_weather_slot_btn3 = $"../single_race_screen/Control/singlerace_panel4/weather_settings/wsettings_label2/wsettings1_radio3"
@onready var sr_weather_slot_btn4 = $"../single_race_screen/Control/singlerace_panel4/weather_settings/wsettings_label2/wsettings1_radio4"
@onready var sr_weather_slot_btn5 = $"../single_race_screen/Control/singlerace_panel4/weather_settings/wsettings_label2/wsettings1_radio5"

@onready var sr_start_type_btn1 = $"../single_race_screen/Control/singlerace_panel5/starttype_settings/wsettings_label1/stsettings1_radio1"
@onready var sr_start_type_btn2 = $"../single_race_screen/Control/singlerace_panel5/starttype_settings/wsettings_label1/stsettings1_radio2"
@onready var sr_start_type_btn3 = $"../single_race_screen/Control/singlerace_panel5/starttype_settings/wsettings_label1/stsettings1_radio3"

@onready var sr_mandatory_pitstop_btn1 = $"../single_race_screen/Control/singlerace_panel6/pitstop_settings/pssettings_label1/pssettings1_radio1"
@onready var sr_mandatory_pitstop_btn2 = $"../single_race_screen/Control/singlerace_panel6/pitstop_settings/pssettings_label1/pssettings1_radio2"
@onready var sr_mandatory_pitstop_btn3 = $"../single_race_screen/Control/singlerace_panel6/pitstop_settings/pssettings_label1/pssettings1_radio3"
@onready var sr_mandatory_pitstop_btn4 = $"../single_race_screen/Control/singlerace_panel6/pitstop_settings/pssettings_label1/pssettings1_radio4"
@onready var sr_mandatory_pitstop_btn5 = $"../single_race_screen/Control/singlerace_panel6/pitstop_settings/pssettings_label1/pssettings1_radio5"

@onready var sr_tire_btn1 = $"../single_race_screen/Control/singlerace_panel7/tirefuel_settings/tfsettings_label1/tfsettings1_radio1"
@onready var sr_tire_btn2 = $"../single_race_screen/Control/singlerace_panel7/tirefuel_settings/tfsettings_label1/tfsettings1_radio2"
@onready var sr_tire_btn3 = $"../single_race_screen/Control/singlerace_panel7/tirefuel_settings/tfsettings_label1/tfsettings1_radio3"
@onready var sr_tire_btn4 = $"../single_race_screen/Control/singlerace_panel7/tirefuel_settings/tfsettings_label1/tfsettings1_radio4"
@onready var sr_tire_btn5 = $"../single_race_screen/Control/singlerace_panel7/tirefuel_settings/tfsettings_label1/tfsettings1_radio5"
@onready var sr_tire_btn6 = $"../single_race_screen/Control/singlerace_panel7/tirefuel_settings/tfsettings_label1/tfsettings1_radio6"
@onready var sr_tire_btn7 = $"../single_race_screen/Control/singlerace_panel7/tirefuel_settings/tfsettings_label1/tfsettings1_radio7"

@onready var sr_fuel_btn1 = $"../single_race_screen/Control/singlerace_panel7/tirefuel_settings/tfsettings_label2/tfsettings2_radio1"
@onready var sr_fuel_btn2 = $"../single_race_screen/Control/singlerace_panel7/tirefuel_settings/tfsettings_label2/tfsettings2_radio2"
@onready var sr_fuel_btn3 = $"../single_race_screen/Control/singlerace_panel7/tirefuel_settings/tfsettings_label2/tfsettings2_radio3"
@onready var sr_fuel_btn4 = $"../single_race_screen/Control/singlerace_panel7/tirefuel_settings/tfsettings_label2/tfsettings2_radio4"
@onready var sr_fuel_btn5 = $"../single_race_screen/Control/singlerace_panel7/tirefuel_settings/tfsettings_label2/tfsettings2_radio5"
@onready var sr_fuel_btn6 = $"../single_race_screen/Control/singlerace_panel7/tirefuel_settings/tfsettings_label2/tfsettings2_radio6"
@onready var sr_fuel_btn7 = $"../single_race_screen/Control/singlerace_panel7/tirefuel_settings/tfsettings_label2/tfsettings2_radio7"

@onready var sr_fcy_btn1 = $"../single_race_screen/Control/singlerace_panel8/fcy_settings/fcysettings_label1/fcysettings1_radio1"
@onready var sr_fcy_btn2 = $"../single_race_screen/Control/singlerace_panel8/fcy_settings/fcysettings_label1/fcysettings1_radio2"
@onready var sr_fcy_btn3 = $"../single_race_screen/Control/singlerace_panel8/fcy_settings/fcysettings_label1/fcysettings1_radio3"

@onready var sr_sfcy_btn1 = $"../single_race_screen/Control/singlerace_panel9/sfcy_settings/sfcysettings_label1/sfcysettings1_radio1"
@onready var sr_sfcy_btn2 = $"../single_race_screen/Control/singlerace_panel9/sfcy_settings/sfcysettings_label1/sfcysettings1_radio2"
@onready var sr_sfcy_btn3 = $"../single_race_screen/Control/singlerace_panel9/sfcy_settings/sfcysettings_label1/sfcysettings1_radio3"
@onready var sr_sfcy_btn4 = $"../single_race_screen/Control/singlerace_panel9/sfcy_settings/sfcysettings_label1/sfcysettings1_radio4"
@onready var sr_sfcy_btn5 = $"../single_race_screen/Control/singlerace_panel9/sfcy_settings/sfcysettings_label1/sfcysettings1_radio5"
