extends Node

var kart_tracks = ['Buskerud Kart Long', 'Buskerud Kart Short', 'Granja Vianna Stage 2',
'Granja Viana Kart 101', 'Granja Viana Kart 102', 'Granja Viana Kart 121', 'Interlagos Kart One',
'Interlagos Kart Two','Interlagos Kart Three', 'Londrina Kart One', 'Londrina Kart Two',
'Ortona Kart One', 'Ortona Kart Two', 'Ortona Kart Three', 'Ortona Kart Four', 'Speedland Kart 1',
'Speedland Kart 2', 'Speedland Kart 3', 'Speedland Kart 4']

var rx_tracks = ["Ascurra RX", "Tikki RX", "Foz", "Barcelona RX", "Hockenheim Rallycross",
"Spa RX", "Nurburgring RX", "Ascurra Dirt", "Tikki Tarmac", "Foz", "Tikki Dirt 2"]

var normal_tracks = ['Adelaide', 'Adelaide 1988', 'Azure Circuit', 'Barcelona (no chicane)',
'Barcelona GP', 'Barcelona National', 'Barcelona 1991', 'Bathurst 2020', 'Bathurst 1983', 'Brands Hatch', 'Brands Hatch Indy', 'Brasilia Full',
'Brasilia Outer', 'Buenos Aires no.6 S', 'Buenos Aires no.6', 'Buenos Aires no.7', 'Buenos Aires no.8',
'Buenos Aires no.9', 'Buenos Aires no.12', 'Buenos Aires no.15', 'Canadian Motorsport Park' ,'Cadwell Park',
'Campo Grande', 'Cascais', 'Cascais Alternate', 'Cascais 1988', 'Cascavel', 'Cleveland GP', 'Curitiba', 'Curitiba Outer',
'Curvelo Long', 'Curvelo Short', 'Cordoba no.4', 'Cordoba TC', 'Cordoba no.2', 'Daytona Sports Car',
'Daytona Nascar Course', 'Daytona Nascar Tri-Oval', 'Donington GP',
'Donington National', 'Fontana Oval', 'Fontana Sports Car', 'Galeao Airport',
'Gateway Oval', 'Gateway (short)', 'Gateway (long)', 'Goiania', 'Goiania short', 'Goiania External',
'Guapore', 'Hockenheim', 'Hockenheim National', 'Hockenheim Short A',
'Hockenheim Short B', 'Hockenheim 2001', 'Hockenheim 1988',
"Le Mans (24 Heures du Mans)", "Le Mans (Bugatti)", 'Hockenheim 1988 (short)', 'Hockenheim 1977', 'Ibarra Yahuarcocha',
'Ibarra Reverse', 'Imola', 'Imola 2001', 'Imola 1988', 'Imola 1972',
'Indianapolis Road Course', 'Indianapolis Oval', 'Interlagos GP', 'Interlagos 1976',
'Interlagos 1978 Outer', 'Interlagos 1991', 'Interlagos 1993', 'Jacarepagua 2005', 'Jacarepagua 1988',
'Jacarepagua 2005 Oval', 'Jacarepagua 2012 SCB', 'Jacarepagua 2012 (short)',
'Jerez Moto', 'Jerez Chicane', 'Jerez 1988', 'Kansai GP', 'Kansai West', 'Kansai Eest', 'Kansai Classic',
'Kyalami', 'Kyalami 1976', 'Laguna Seca 2020', 'Londrina Short', 'Londrina Long',
'Long Beach', 'Montreal', 'Montreal 1988', 'Montreal 1991', 'Monza', 'Monza Junior', 'Monza 1991',
'Monza 1971', 'Monza 1971 Junior', 'Monza 1971 10k', 'Monza 1971 10k (no chicane)', 'Nordschleife 2020',
'Nordschleife 24h 2025', 'Nordschleife 24h 2020', 'Nurburgring GP 2020', 'Nurburgring Veedol 2020',
'Nurburgring Sprint 2020', 'Nurburgring Sprint S 2020', 'Gesamtstrecke 1971', 'Betonschleife 1971',
'Nordschleife 1971', 'Sudschleife 1971', 'Oulton Park International', 'Oulton Park Island',
'Oulton Park Fosters', 'Oulton Park Classic', 'Road America', 'Road America (bend)', 'Road Atlanta Raceway',
'Salvador Street Circuit', 'Santa Cruz do Sul', 'Sebring International Raceway', 'Silverstone', 'Silverstone International',
'Silverstone National', 'Silverstone 2001', 'Silverstone International 2001', 'Silverstone National 2001',
'Silverstone 1991', 'Silverstone 1975', 'Silverstone 1975 (no chicane)', 'Snetterton 300', 'Snetterton 200',
'Snetterton 100', 'Spa-Franchorchamps 2022', 'Spa-Franchorchamps 2020', 'Spa-Franchorchamps 1993',
'Spa-Franchorchamps 1970', 'Spa-Franchorchamps 1970 1000km', 'Spielberg', 'Spielberg short',
'Spielberg 1974', 'Spielberg 1977', 'Taruma International',
'Taruma Chicane', 'Termas de Rio Hondo', 'Velo Citta', 'Velo Citta Track Day',
'Velo Citta Club Day', 'Velo park 2017', 'Velopark 2010', 'VIRginia International Full',
'VIRginia International Grand', 'VIRginia International North', 'VIRginia International Patriot',
'Watkins Glen GP', 'Watkins Glen GP (inner loop)', 'Watkins Glen short', 'Watkins Glen short (inner loop)']
